/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoleRouteImport } from './routes/$role'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RoleIndexRouteImport } from './routes/$role.index'
import { Route as RoleSectionRouteImport } from './routes/$role.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleIndexRoute = RoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoleRoute,
} as any)
const RoleSectionRoute = RoleSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => RoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$role': typeof RoleRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$role/$section': typeof RoleSectionRoute
  '/$role/': typeof RoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$role/$section': typeof RoleSectionRoute
  '/$role': typeof RoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$role': typeof RoleRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$role/$section': typeof RoleSectionRoute
  '/$role/': typeof RoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$role'
    | '/complete-profile'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/$role/$section'
    | '/$role/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-profile'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/$role/$section'
    | '/$role'
  id:
    | '__root__'
    | '/'
    | '/$role'
    | '/complete-profile'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/$role/$section'
    | '/$role/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoleRoute: typeof RoleRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$role': {
      id: '/$role'
      path: '/$role'
      fullPath: '/$role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$role/': {
      id: '/$role/'
      path: '/'
      fullPath: '/$role/'
      preLoaderRoute: typeof RoleIndexRouteImport
      parentRoute: typeof RoleRoute
    }
    '/$role/$section': {
      id: '/$role/$section'
      path: '/$section'
      fullPath: '/$role/$section'
      preLoaderRoute: typeof RoleSectionRouteImport
      parentRoute: typeof RoleRoute
    }
  }
}

interface RoleRouteChildren {
  RoleSectionRoute: typeof RoleSectionRoute
  RoleIndexRoute: typeof RoleIndexRoute
}

const RoleRouteChildren: RoleRouteChildren = {
  RoleSectionRoute: RoleSectionRoute,
  RoleIndexRoute: RoleIndexRoute,
}

const RoleRouteWithChildren = RoleRoute._addFileChildren(RoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoleRoute: RoleRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
